import Head from "next/head";
import Navbar from "../components/Navbar";
import { getSession, useSession } from "next-auth/react";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import Brands from "../components/Brands";
import MoviesCollection from "../components/MoviesCollection";

export default function Home({
  popularMovies,
  popularShows,
  top_ratedMovies,
  top_ratedShows,
}) {
  const { data: session } = useSession();

  // TEST
  //   GOOGLE_CLIENT_ID=759486537762-bq3pa2eoge3d8vl13kjt4gc437csa17m.apps.googleusercontent.com
  // GOOGLE_CLIENT_SECRET=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

  // REAL
  //   GOOGLE_CLIENT_ID=759486537762-o74ulf605p0eg6vlfkuaaldc0ro944c9.apps.googleusercontent.com
  // GOOGLE_CLIENT_SECRET= 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

  return (
    <div>
      <Head>
        <title>Disney+</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {!session ? (
        <Hero />
      ) : (
        <main className="relative  min-h-screen after:bg-home after:bg-center after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]">
          <Slider />
          <Brands />
          <MoviesCollection
            results={popularMovies}
            title="Marvel Cinematic Universe: Phase one"
          />
        </main>
      )}
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  const [
    popularMoviesRes,
    popularShowsRes,
    top_ratedMoviesRes,
    top_ratedShowsRes,
  ] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/movie/latest?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
  ]);
  const [popularMovies, popularShows, top_ratedMovies, top_ratedShows] =
    await Promise.all([
      popularMoviesRes.json(),
      popularShowsRes.json(),
      top_ratedMoviesRes.json(),
      top_ratedShowsRes.json(),
    ]);

  return {
    props: {
      session,
      popularMovies: popularMovies,
    },
  };
}
